apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydeployment
  name: myservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mydeployment
status:
  loadBalancer: {}
